### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Eduardo-Vieira** [nirav-tukadiya/Biometric-Compat#1]
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0-rc01] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0-beta01] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:19:5-106:19 to override.

your lib is conflicting with that of the android package.

**Comment by nirav-tukadiya** [comment]
The library has been refactored with AndroidX.  Either you can refactor your project to androidx or you can just ignore the warning by adding `tools:replace="android:appComponentFactory" ` in AndroidManifest.xml file.
